// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ829wQisSwv-1MMmTemY2BtZSG7P9wrg',
    appId: '1:713847343535:web:8f8ae39b0b5660a303875a',
    messagingSenderId: '713847343535',
    projectId: 'newsapp-238f0',
    authDomain: 'newsapp-238f0.firebaseapp.com',
    storageBucket: 'newsapp-238f0.firebasestorage.app',
    measurementId: 'G-2ZLP7NYN2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxDrIg7swRTW19WrTQEl7e0tU1b_6kBJ8',
    appId: '1:713847343535:android:c938975f446915d503875a',
    messagingSenderId: '713847343535',
    projectId: 'newsapp-238f0',
    storageBucket: 'newsapp-238f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFbcassKiyaf8wmxATo_qlykPpVvZDKLU',
    appId: '1:713847343535:ios:c6aefda8d6b6850a03875a',
    messagingSenderId: '713847343535',
    projectId: 'newsapp-238f0',
    storageBucket: 'newsapp-238f0.firebasestorage.app',
    iosBundleId: 'com.example.newsAppTekup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFbcassKiyaf8wmxATo_qlykPpVvZDKLU',
    appId: '1:713847343535:ios:c6aefda8d6b6850a03875a',
    messagingSenderId: '713847343535',
    projectId: 'newsapp-238f0',
    storageBucket: 'newsapp-238f0.firebasestorage.app',
    iosBundleId: 'com.example.newsAppTekup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ829wQisSwv-1MMmTemY2BtZSG7P9wrg',
    appId: '1:713847343535:web:d2e2c418d44732cb03875a',
    messagingSenderId: '713847343535',
    projectId: 'newsapp-238f0',
    authDomain: 'newsapp-238f0.firebaseapp.com',
    storageBucket: 'newsapp-238f0.firebasestorage.app',
    measurementId: 'G-86ED1Y0GTP',
  );
}
